### PR TITLE
fix return type of EnsembleThreads

### PR DESCRIPTION
**Pull request by ChrisRackauckas**

### CODE REVIEW

**Review by YingboMa — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
Downstream failure is https://github.com/SciML/SciMLBase.jl/pull/47 @Vaibhavdixit02 hmm

**Comment by Vaibhavdixit02** [comment]
But the tests passed in that PR so that's weird?

I will try to take a look at what's causing this unless someone beats me to it

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/pull/52 is it.

**Comment by ChrisRackauckas** [comment]
That regression test didn't exist in this repo until now.

**Comment by Vaibhavdixit02** [comment]
👍

**Pull request merged**
