### PR TITLE
fix: don't rely on RAT internals in EnsembleSolution indexing

### PR DESCRIPTION
**Pull request by AayushSabharwal**
## Checklist

- [ ] Appropriate tests were added
- [ ] Any code changes were done in a way that does not break public API
- [ ] All documentation related to code changes were updated
- [ ] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ ] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What does this fix?

**Comment by AayushSabharwal** [comment]
https://github.com/SciML/ModelingToolkit.jl/actions/runs/8950984751/job/24586851845#step:6:1792

**Comment by ChrisRackauckas** [comment]
`Sparse(AutoForwardDiff())`, but how that happened to get an incompatible version is a mystery right now @gdalle @Vaibhavdixit02 @avik-pal

**Comment by gdalle** [comment]
I have no clue what RAT or EnsembleSolution are, or how sparse autodiff is even involved here, can someone brief me in case I'm the one who should help?

**Comment by AayushSabharwal** [comment]
I think Chris was referring to https://github.com/JuliaSymbolics/Symbolics.jl/pull/1129 actually, specifically [this](https://github.com/JuliaSymbolics/Symbolics.jl/actions/runs/8968453379/job/24627884759#step:7:1335) failure

**Comment by gdalle** [comment]
I answered on the other issue ;)

**Pull request merged**
