### PR TITLE
fix deprecated indexing in EnsembleSummary plot recipe

### PR DESCRIPTION
**Pull request by SebastianM-C**
I missed this ones.
@AayushSabharwal is this ok? It seems a bit odd to need `sim.u.u[1]` at first sight.

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Yeah that is weird. `VectorOfArray`s shouldn't have a `VectorOfArray` as `u`. I'll investigate this further

**Comment by SebastianM-C** [comment]
I'm not sure if it helps, but I was wondering if this is due to the fact that individual ODESolutions are no longer AbstractArrays and the recipes relied on this to distinguish between scalar and vector cases, as for ensemble you can have scalar differential equations or output functions that return scalars.

**Comment by AayushSabharwal** [comment]
This does seem to be what is required here. I'm not fully on board with the `AbstractVectorOfArray.u` being another `AbstractVectorOfArray` thing that's going on, but if it works it works I guess.

**Comment by SebastianM-C** [comment]
Should this be merged?

cc @ChrisRackauckas

**Pull request merged**
