### PR TITLE
Allow hooks for observed symbol indexing

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t σ ρ β
@variables x(t) y(t) z(t) δ(t) Ω(t)
D = Differential(t)

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

lorenz1 = ODESystem(eqs,name=:lorenz1)
lorenz2 = ODESystem(eqs,name=:lorenz2)

@variables a
@parameters γ
connections = [0 ~ lorenz1.x + lorenz2.y + a*γ]
connected = ODESystem(connections,t,[a],[γ],systems=[lorenz1,lorenz2])

u0 = [lorenz1.x => 1.0,
      lorenz1.y => 0.0,
      lorenz1.z => 0.0,
      lorenz2.x => 0.0,
      lorenz2.y => 1.0,
      lorenz2.z => 0.0,
      a => 2.0]

p  = [lorenz1.σ => 10.0,
      lorenz1.ρ => 28.0,
      lorenz1.β => 8/3,
      lorenz2.σ => 10.0,
      lorenz2.ρ => 28.0,
      lorenz2.β => 8/3,
      γ => 2.0]

tspan = (0.0,100.0)
prob = ODEProblem(connected,u0,tspan,p)
sol = solve(prob,Rodas5())

sol[lorenz1.x]
sol[lorenz1.x,2]
sol[lorenz1.x,:]
sol[lorenz1.x,1:5]
sol[δ,1:5] # Indexing symbol δ is unknown.

# Assume δ = a*lorenz1.x + lorenz2.y
function SciMLBase.DEFAULT_OBSERVED(sym, u)
      if sym === δ
            u[7]*u[1] + u[5]
      elseif sym === Ω
            u[7]
      else
            error("Indexing symbol $sym is unknown.")
      end
end

sol[δ,1:5] # success!
sol[Ω] # success!

using Plots
plot(sol,vars=(lorenz2.x,lorenz2.z))
plot(sol,vars=(δ,lorenz2.z))
plot(sol,vars=(δ,Ω)) # made a heart!
```

plot

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Should we give a form with vector of vector `u`? @YingboMa

**Comment by ChrisRackauckas** [comment]
Downstream tests revealed we to be much more careful with independent variable naming, so that'll get a thing too.

**Comment by ChrisRackauckas** [comment]
```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t σ ρ β
@variables x(t) y(t) z(t) δ(t) Ω(t)
D = Differential(t)

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

lorenz1 = ODESystem(eqs,name=:lorenz1)
lorenz2 = ODESystem(eqs,name=:lorenz2)

@variables a
@parameters γ
connections = [0 ~ lorenz1.x + lorenz2.y + a*γ]
connected = ODESystem(connections,t,[a],[γ],systems=[lorenz1,lorenz2])

u0 = [lorenz1.x => 1.0,
      lorenz1.y => 0.0,
      lorenz1.z => 0.0,
      lorenz2.x => 0.0,
      lorenz2.y => 1.0,
      lorenz2.z => 0.0,
      a => 2.0]

p  = [lorenz1.σ => 10.0,
      lorenz1.ρ => 28.0,
      lorenz1.β => 8/3,
      lorenz2.σ => 10.0,
      lorenz2.ρ => 28.0,
      lorenz2.β => 8/3,
      γ => 2.0]

tspan = (0.0,100.0)
prob = ODEProblem(connected,u0,tspan,p)
sol = solve(prob,Rodas5())

sol[lorenz1.x]
sol[lorenz1.x,2]
sol[lorenz1.x,:]
sol[lorenz1.x,1:5]
sol[δ,1:5] # Indexing symbol δ is unknown.

# Assume δ = a*lorenz1.x + lorenz2.y
function SciMLBase.DEFAULT_OBSERVED(sym, u)
      if sym === δ
            u[7]*u[1] + u[5]
      elseif sym === Ω
            u[7]
      else
            error("Indexing symbol $sym is unknown.")
      end
end

sol[δ,1:5] # success!
sol[Ω] # success!

using Plots
plot(sol,vars=(lorenz2.x,lorenz2.z))
savefig("plot1.png")
plot(sol,vars=(δ,lorenz2.z))
savefig("plot2.png")
plot(sol,vars=(δ,Ω)) # made a heart!
savefig("plot3.png")
plot(sol,vars=Ω)
savefig("plot4.png")
plot(sol,vars=(t,Ω))
savefig("plot5.png")
```

plot1
plot2
plot3
plot4
plot5

**Comment by ChrisRackauckas** [comment]
For reference the plot recipe needs a full rewrite, but I'll leave that for later. The reason the code is so crazy is because it's basically faking support for exactly this functionality we now have. Every single line is a bunch of if statements of the form:

1. If it's an index, yes!
2. If it's a symbol, check if the symbol exists
3. If the symbol doesn't exist, is it the independent variable?
4. Well if nothing is there, guess it's the independent variable?

Which means it's really just `sol[x]` at a bunch of those lines. So with all of this functionality it can be rewritten to be like 1/5 of the code and 400x more legible, which is a good sign for this functionality. But I don't plan to do that today since the plots show that a few hacks around it works. And the DiffEqBase tests rightfully caught any independent variable issues, which leads to the fact that we also need the symbolic libraries to define `indepsym` instead of just guessing `t` all of the time.

The `t` default in plotting is left there to just not be breaking.

**Comment by YingboMa** [comment]
> Should we give a form with vector of vector u for observed?
> observed(sym,u::Vector{<:AbstractArray})

I assume this is for a time series? I don't think we need this. Map on observed won't be too bad. Also, can we have
```julia
struct AllObserved end
observed(AllObserved(), u)
```
to get all the observed variables?

PS: the heart looks really nice!

**Comment by ChrisRackauckas** [comment]
I was just writing up the issue: https://github.com/SciML/SciMLBase.jl/issues/12 .

**Review by YingboMa — APPROVED** [review]
LGTM

**Pull request merged**
