### PR TITLE
Adds field indicating integrality of the opt vars

### LINKED ISSUE #270: Add `int` field to `OptimizationProblem`
A field indicating which variables have to fulfil an integrality constraint. If the bounds are `[0,1]` it is a binary variable.

### PR DESCRIPTION
**Pull request by ValentinKaisermayer**
closes #270

### CODE REVIEW

**Review by Vaibhavdixit02 — APPROVED** [review]
Looks good, but I am curious about how you plan to use it. Do you have an example you tested this out on that you can show?

**Comment by ValentinKaisermayer** [comment]
> Looks good, but I am curious about how you plan to use it. Do you have an example you tested this out on that you can show?

I'm working on it, see https://github.com/SciML/ModelingToolkit.jl/issues/1786

**Comment by ValentinKaisermayer** [comment]
For instance, now it is trivial to add support for it with `NOMAD.jl`, in:
https://github.com/SciML/Optimization.jl/blob/b67636eeb5ee854fa53569e67bff3a21c5ed7a97/lib/OptimizationNOMAD/src/OptimizationNOMAD.jl#L80

Depending on the variable bounds `lb` and `ub` and the integrality indicator `int` the variable types can be inferred and are either `"R"`, `"B"` or `"I"`.

`MTK` got support for binary and integer variable metadata in https://github.com/SciML/ModelingToolkit.jl/pull/1798.
And I'm planning to add support for other MOI solvers like `CBC`, or `Gurobi`, that support such variable types in  https://github.com/SciML/Optimization.jl/pull/381.

It should be just a matter of connecting all of it now. 😃

**Comment by Vaibhavdixit02** [comment]
I see, cool!

**Pull request merged**
