### PR TITLE
add missing commas

### PR DESCRIPTION
**Pull request by isaacsas**
@ChrisRackauckas some commas were missing that I didn't notice. I can confirm SciMLBase can be loaded now (it will error with the previous PR).

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
I already fixed these.

**Comment by isaacsas** [comment]
Ahh, cool. Thanks for catching that then!

**Comment by isaacsas** [comment]
Sorry I missed it...

**Comment by ChrisRackauckas** [comment]
No worries. Our test suite covers so much that it's easy to poke at from the web interface on the phone 😅

**Comment by isaacsas** [comment]
Nice!

**Pull request closed without merging**
