### PR TITLE
Revert "Add symbol based indexing for interpolated solutions"

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Reverts SciML/SciMLBase.jl#66

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@sharanry see the test failure of last one.

**Comment by sharanry** [comment]
@ChrisRackauckas Are you talking about [this](https://github.com/SciML/SciMLBase.jl/runs/2992966204#step:6:2585)? It feels unrelated. Not sure.

**Comment by sharanry** [comment]
Also, I guess I will have to make a new PR?

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/runs/2992375777

**Comment by sharanry** [comment]
That was a old run before you restarted the workflows.

**Comment by ChrisRackauckas** [comment]
Oh oops, so then it's fine. This is clean 😅

**Comment by sharanry** [comment]
This is the latest run where only DiffEqFlux fails due to what I suspect is a unrelated issue. https://github.com/SciML/SciMLBase.jl/actions/runs/1002138361

**Pull request merged**
