### PR TITLE
Improved Symbolic Indexing

### PR DESCRIPTION
**Pull request by AayushSabharwal**
Uses SymbolicIndexingInterface.jl
Refer to https://github.com/SciML/ModelingToolkit.jl/pull/1988

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
I'm fairly certain the rest of the tests will only pass once MTK gets bumped and this can depend on the new version

**Comment by AayushSabharwal** [comment]
If paramsyms/indepsym is passed to the SciMLFunction, then I guess there isn't a reason to not fallback to it

**Comment by AayushSabharwal** [comment]
This needs RecursiveArrayTools for tests to pass as well

**Comment by AayushSabharwal** [comment]
I didn't realise that some functions contain the sys but shouldn't use it for indexing, so it complains that they don't implement the interface. There's no way (as of now) to check if the interface is implemented, so it looks like defaulting `is_state_sym(::Any, _) = false` should do the trick

**Comment by AayushSabharwal** [comment]
Now this should be compatible with previous MTK versions as well

**Comment by AayushSabharwal** [comment]
Rerunning CI here _should_ make everything passed 🤞🏻

**Comment by ChrisRackauckas** [comment]
Sounds suspicious.

**Comment by AayushSabharwal** [comment]
Should I close this to not waste CI then reopen once its tagged?

**Comment by ChrisRackauckas** [comment]
Told you, sus.

**Comment by ChrisRackauckas** [comment]
Just gotta wait a bit haha https://github.com/JuliaRegistries/General/pull/74053

**Comment by AayushSabharwal** [comment]
Dunno what is up with me today 😅 a bit all over the place

**Comment by AayushSabharwal** [comment]
Finally merged

**Comment by AayushSabharwal** [comment]
Apparently reopening doesn't rerun CI

**Comment by ChrisRackauckas** [comment]
Still failing

**Comment by AayushSabharwal** [comment]
That failure confuses me. In the system at `MTK/test/components.jl:99`, why does `states(sys)` say that there are two states (`capacitor.v` and `capacitor.i`) but the solution is Nx1 (timeseries of one element)

**Comment by ChrisRackauckas** [comment]
The other must be an observed variable. How are those treated?

**Comment by AayushSabharwal** [comment]
If a symbol doesn't match a state variable, it falls back to using `observed` as it did before. However, the system says its a state variable, so it never falls back.

It seems `ODAEProblem` does some additional simplification, which seems backward to me. Why would a problem modify the system? In any case, it makes the information that the system has invalid, which causes problems

**Comment by ChrisRackauckas** [comment]
Might need to wait until @YingboMa is back

**Comment by xtalax** [comment]
How is this going - this being merged seems like a prerequisite for `save_idxs`  as `SymbolicIndexingInterface` seems to solve a lot of the same problems

**Comment by oscardssmith** [comment]
it looks like this just needs a format

**Comment by ChrisRackauckas** [comment]
Boom

**Comment by AayushSabharwal** [comment]
Is the ODAEProblem stuff fixed?

**Comment by YingboMa** [comment]
Yes

**Comment by oscardssmith** [comment]
See https://github.com/SciML/SciMLBase.jl/pull/379 which makes this also work for `DAESolution`.

**Pull request merged**
