### PR TITLE
Fix ambiguities

### PR DESCRIPTION
**Pull request by SebastianM-C**
I removed the `::Function` restriction as mentioned in https://github.com/SciML/SciMLBase.jl/issues/42#issuecomment-808923055

### CODE REVIEW

**Comment by devmotion** [comment]
Maybe you could add a test of `detect_ambiguities` to avoid regressions and to ensure that no new ambiguities are added?

**Comment by SebastianM-C** [comment]
There already is one (it's the first test actually)
https://github.com/SciML/SciMLBase.jl/blob/15df15622631a58a7dc943515a3902e65859cb6c/test/runtests.jl#L6

**Comment by devmotion** [comment]
Oh OK, I didn't notice this, somehow I just assumed all tests pass on the master branch :smile:

**Review by devmotion — APPROVED** [review]
LGTM :+1:

**Comment by isaacsas** [comment]
FWIW the DiffEqJump downstream failure is a dumb test bug (there is apparently a RNG-dependent outcome for a test...).

**Comment by SebastianM-C** [comment]
@isaacsas Thanks, I was not sure what was the problem with that.

**Pull request merged**
