### PR TITLE
Add `strip_cache` for DECache

### PR DESCRIPTION
**Pull request by jClugstor**
## Checklist

- [ x] Appropriate tests were added
- [ x] Any code changes were done in a way that does not break public API
- [ x] All documentation related to code changes were updated
- [ x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [ x] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Create a test that catches this.

**Comment by ChrisRackauckas** [comment]
why is this needed here? Isn't it just internal to OrdinaryDiffEq?

**Comment by jClugstor** [comment]
I wasn't sure if there were other interpolation types in SciMLBase that would have caches. 
Is it better to just put 
```julia
function strip_cache(cache::OrdinaryDiffEqCache)
    # most caches don't have jac_config or grad_config
    cache
end
```
in to OrdinaryDiffEq?

**Comment by ChrisRackauckas** [comment]
You define a special strip_interpolation in OrdianryDiffEq, and that will have a function in there to strip caches, and then that is defined as just a helper which uses knowledge of how caches in OrdinaryDiffEq work. I don't see that as generic at all though.

**Comment by jClugstor** [comment]
I was thinking something like this:
```julia
function SciMLBase.strip_interpolation(id::InterpolationData)
    cache = id.cache
    
    cache = strip_cache(cache)

    InterpolationData(nothing, id.timeseries,
        id.ts,
        id.ks,
        id.alg_choice,
        id.dense,
        cache,
        id.differential_vars,
        id.sensitivitymode)
end

function strip_cache(cache::OrdinaryDiffEqCache)
    # most caches don't have jac_config or grad_config
    cache
end
```
and then I can define `strip_cache` specifically for the cache types that need `jac_config` and `grad_config` to be taken out.

**Pull request closed without merging**
