### PR TITLE
feat: add support for ParameterIndexingProxy

### PR DESCRIPTION
**Pull request by AayushSabharwal**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by AayushSabharwal** [comment]
Requires https://github.com/SciML/SymbolicIndexingInterface.jl/pull/26

**Comment by AayushSabharwal** [comment]
No, a badly written test I think 😅

**Comment by AayushSabharwal** [comment]
Requires https://github.com/SciML/SymbolicIndexingInterface.jl to be merged and tagged

**Comment by ChrisRackauckas** [comment]
All SciMLSensitivity tests just started failing? https://github.com/SciML/SciMLBase.jl/actions/runs/7567194901/job/20605897599?pr=584#step:6:1328 @AayushSabharwal was this something form RAT?

**Comment by AayushSabharwal** [comment]
Yep. It doesn't like some of the adjoints again.

**Comment by AayushSabharwal** [comment]
SciMLSensitivity won't pass until after https://github.com/SciML/RecursiveArrayTools.jl/pull/337

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal make sure to follow up on the JumpProcesses.jl downstream.

**Pull request merged**
