### PR TITLE
fix mean and cov for integer solution values in Ensembles

### PR DESCRIPTION
**Pull request by isaacsas**
Fixes https://github.com/SciML/DifferentialEquations.jl/issues/731 locally at least. CC @augustinas1

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
add a test?

**Comment by isaacsas** [comment]
Here or DiffEqJump?

**Comment by ChrisRackauckas** [comment]
Either. Probably here, since I can see that `/1` being deleted by someone so there should be an immediate test that says no.

BTW, we should add DiffEqJump to the list of downstream tests.

**Comment by isaacsas** [comment]
Ok. I’ll update with a test here and update the GitHub action tomorrow morning (away from my computer now).

**Comment by ChrisRackauckas** [comment]
There's now a setup for easier downstream tests directly from SciMLBase for adding this kind of thing,.

**Comment by isaacsas** [comment]
@ChrisRackauckas if tests pass this should be good.

**Comment by isaacsas** [comment]
Decided to make it a bit more general since this is closer to the original issue. (i.e. integers actually worked fine in some cases, just not with broadcasting which wasn't used for flat array inputs like I previously had...)

**Pull request merged**
