### PR TITLE
Add PyCall extension

### PR DESCRIPTION
**Pull request by LilithHafner**

### CODE REVIEW

**Comment by LilithHafner** [comment]
I'm not sure how to make sense of the test failures. The [last merged PR](https://github.com/SciML/SciMLBase.jl/pull/503) had 55/72 successes, this has 54/71. Tests pass locally for me.

**Comment by ChrisRackauckas** [comment]
It's not you it's me 😅 

We just did the v2 release yesterday, and this is package used by hundreds of other packages so the breaking update will take awhile to propagate through all of the downstream packages and pass.

**Comment by LilithHafner** [comment]
What's the status here? Is there anything I should do to help?

**Comment by ChrisRackauckas** [comment]
The tests are failing because it doesn't find pyjulia to be installed. Try moving the conda pip stuff to before the pycall is loaded? Somehow it needs to install that package on the Julia side to test it

**Comment by LilithHafner** [comment]
Ah, lovely! And I can use [this CI failure](https://github.com/SciML/SciMLBase.jl/actions/runs/6371083896/job/17292733089?pr=502) as a guide, thanks!

**Comment by LilithHafner** [comment]
Python tests pass! 🎉

**Comment by ChrisRackauckas** [comment]
Awesome, thanks for pushing through it!

**Pull request merged**
