### PR TITLE
allow different number of out-of-place args for isinplace

### PR DESCRIPTION
**Pull request by ranocha**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API
  
## Additional context

This helps us at https://github.com/SKopecz/PositiveIntegrators.jl

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
What's this for?

**Comment by ranocha** [comment]
For PositiveIntegrators.jl, we need to partition the ODE right-hand side into (positive) production and (negative) destruction terms. Up to now, we have used two functions for this that can either be in-place (like `production!(production_terms, u, p, t)`) or out-of-place (like `production_terms = production(u, p, t)`). Thus, we could use `isinplace` as it is. To improve the performance of some applications, we want to use a single function with in-place form `rhs!(production_terms, destruction_terms, u, p, t)` and out-of-place form `production_terms, destruction_terms = rhs(u, p, t)`. With the current version of `isinplace`, it's hardcoded that the out-of-place form has exactly one argument less than the in-place form. Thus, we cannot use it as it is right now for our new desired dispatches.

**Comment by ranocha** [comment]
The downgrade action fails already on `master`

**Comment by ranocha** [comment]
Is that something we can support with SciMLBase.jl, @ChrisRackauckas? The only other option we have is to replicate code in PositiveIntegrators.jl.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by ranocha** [comment]
Thanks!

**Pull request merged**
